// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkhAp-lBUWsLhzhaSm_RjhbdWfYvxq6VM',
    appId: '1:613394456110:web:98a541230a5a6c67a409bf',
    messagingSenderId: '613394456110',
    projectId: 'map-41b0f',
    authDomain: 'map-41b0f.firebaseapp.com',
    storageBucket: 'map-41b0f.firebasestorage.app',
    measurementId: 'G-DRSTYWR575',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUw4ScWdF_9duezweP0_XpYTbDSX5-z4',
    appId: '1:613394456110:android:58169917de029d2fa409bf',
    messagingSenderId: '613394456110',
    projectId: 'map-41b0f',
    storageBucket: 'map-41b0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU4bhc89B1p3i7aIDuhzFSUhppqi9utMg',
    appId: '1:613394456110:ios:5a0b335ed5699908a409bf',
    messagingSenderId: '613394456110',
    projectId: 'map-41b0f',
    storageBucket: 'map-41b0f.firebasestorage.app',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU4bhc89B1p3i7aIDuhzFSUhppqi9utMg',
    appId: '1:613394456110:ios:5a0b335ed5699908a409bf',
    messagingSenderId: '613394456110',
    projectId: 'map-41b0f',
    storageBucket: 'map-41b0f.firebasestorage.app',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkhAp-lBUWsLhzhaSm_RjhbdWfYvxq6VM',
    appId: '1:613394456110:web:894885c0fc150965a409bf',
    messagingSenderId: '613394456110',
    projectId: 'map-41b0f',
    authDomain: 'map-41b0f.firebaseapp.com',
    storageBucket: 'map-41b0f.firebasestorage.app',
    measurementId: 'G-2RRXSP9BDH',
  );
}
